name: PartyChat
version: 3.2.6
main: dev.majek.partychat.PartyChat
api-version: 1.16
authors: [ Majekdor ]
description: Easily chat among your friends in a party without any commands.
website: https://majek.dev/partychat
softdepend: [PlaceholderAPI, Essentials, LiteBans, AdvancedBan]
commands:
  partychat:
    description: Toggle party chat or speak in party chat /pc <message>.
    aliases: [pc]
    usage: /partychat <message>
  normalchat:
    description: Send message to normal chat /nc <message>.
    aliases: [nc]
    usage: /normalchat <message>
  party:
    description: Party management commands.
    aliases: [p]
  spy:
    description: Admin spy command.
    aliases: [partyspy]
  pcreload:
    description: Reload the plugin.

permissions:
  partychat.admin:
    description: Allows use of spy and reload command.
    default: op
  partychat.use:
    description: Allows use of PartyChat if use-permissions is enabled in the config.
